language: go
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x

install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/tools/godep
  - godep restore -v

script: ginkgo
